### ISSUE TITLE
add updated Next.js example

### ISSUE THREAD

**Issue by jthegedus** [jthegedus/firebase-gcp-examples#29]
- [ ] add code to repo
- [ ] write blog post
- [ ] publish blog post
- [ ] add post to the example's README.md
- [ ] add post to the index table
- [ ] add post to the Medium ToC post

**Comment by mattgabor** [comment]
hey @jthegedus, I am finding your post & repo in 2020 and I really appreciate the great work you've done here! I was wondering if you'd suggest following the method you described in 2017 that's represented [here](https://github.com/firebase/functions-samples/tree/master/nextjs-with-firebase-hosting) or using the code in this repo? 

This newer implementation looks a lot cleaner, but I wanted to make sure before proceeding since I see `(not working)` in some of the commits

**Comment by jthegedus** [comment]
Hi @mattgabor ,

I would recommend the example in this repo over other two examples (`firebase/functions-samples` or `nextjs/examples/with-firebase-hosting`). I am updating this example again this weekend after the latest 9.3 next.js release so stay tuned for that one.

**Comment by mattgabor** [comment]
awesome, I will check this weekend, thanks for the quick reply :)

**Comment by jthegedus** [comment]
The one in this repo should be good to go, except for changes like this https://cloud.google.com/functions/docs/securing/managing-access-iam#allowing_unauthenticated_function_invocation

**Comment by jthegedus** [comment]
@mattgabor Here is an example using the new Next.js Static Site Generation feature with Firestore. Blog post to come. https://github.com/jthegedus/firebase-gcp-examples/tree/master/hosting-nextjs-ssg

This is not the updated SSR example I promised. Hopefully I can get that figured out this week.

**Comment by jthegedus** [comment]
@mattgabor Please see the new example here https://github.com/jthegedus/firebase-gcp-examples/tree/master/functions-nextjs

**Comment by mattgabor** [comment]
Thanks @jthegedus this looks a lot simpler! I’m looking forward to your updates around auth and interacting with the database, that hasn’t been super straightforward using next

**Comment by joshleong** [comment]
Hi @jthegedus, i've given the new sample a test run.

I'm not sure what my web-app values are for TODO_YOUR_WEB_APP_DEPLOY_TARGET_HERE . I can't find anything about the site value in Firebase Hosting documents.

I wasn't able to run the scripts on my windows machine, but everything seems to have gone smoothly on the Ubuntu machine that I have in Windows when I remove the site value.

The result however is that Firebase Hosting is just serving the standard index.html page, and I'm only able to access the nextjs-server from the Cloud Function URL, in this environment things like next/link are being blocked by permissions again, even though I believe my nextjs-function still has the permissive IAM properties on them.

I'm also not particularly sure what Firebase Datastore to use to get the sample up and running it seems to be that Firebase now has DataStore and Firestore the old real-time database, I don't seem to be able to access the Datastore API from the URL that gets passed too SWR.

**Comment by jthegedus** [comment]
Hi @joshleong I will try my best to explain everything:

`TODO_YOUR_WEB_APP_DEPLOY_TARGET_HERE`: You can create multiple apps in a single Firebase project, this is how you can have an Android, iOS and Web App apps running of the same backend infrastructure. Part of this feature is having multiple Web Apps in a single project. The `site` value is used to identify which WebApp your specific Hosting configuration is pointing at.

![Screen Shot 2020-05-05 at 3 05 53 pm](https://user-images.githubusercontent.com/20798510/81036314-04a69300-8ee2-11ea-902d-4cb7eb03d281.png)

See the `Add another site` button on the right. The setup process will give you the `site: "..."` config you need.

This is referenced in the [`Need to know` section of the example's readme](https://github.com/jthegedus/firebase-gcp-examples/tree/master/functions-nextjs#need-to-know). The Official docs call these deploy `targets`, as it applies to multiple resources (multiple databases, apps etc per project).

>[Firebase Deploy Targets](https://firebase.google.com/docs/cli/targets#set-up-deploy-target-hosting) are used to isolate the Next.js app from the rest of your Firebase project. Since Firebase allows multiple websites, databases etc per project, we want to be explicit about which app we're deploying in our project.

This was added as a way to separate you Next.js application from other sites in your existing project.

---

Which scripts failed on your Windows machine? I didn't test cross-OS, but expected it to work without much change.

---

>The result however is that Firebase Hosting is just serving the standard index.html page, and I'm only able to access the nextjs-server from the Cloud Function URL, in this environment things like next/link are being blocked by permissions again, even though I believe my nextjs-function still has the permissive IAM properties on them.

I have not 1 time run into this issue. I even created a new Firebase project to test this end to end just in case I hit the Cloud Function issues people seem to be having. The only thing that comes to mind is perhaps your `firebase-tools` is out of date. You need version `8.x.x` or more to use Cloud Functions with Firebase today because of the IAM changes.

From https://firebase.google.com/docs/functions/http-events#invoke_an_http_function

>Caution: New HTTP and HTTP callable functions deployed with any Firebase CLI lower than version 7.7.0 are private by default and throw HTTP 403 errors when invoked. Either explicitly make these functions public, or update your Firebase CLI before you deploy any new functions.

--- 

- Firestore is the new database with realtime support.
- RealtimeDB is the old database with realtime support.
- Datastore is the underlying GCP database of Firestore.

You want to use Firestore. It looks like this:

![Screen Shot 2020-05-05 at 3 24 11 pm](https://user-images.githubusercontent.com/20798510/81037022-9a432200-8ee4-11ea-88ea-93f9e83754a4.png)

---

>I don't seem to be able to access the Datastore API from the URL that gets passed too SWR

This should be fixed when you run `npm run deploy` script as the `firebase deploy` will deploy the `firestore.rules` file which sets `read` permissions of the database to allow all reads.

You can check the deploy security rules of the Database in the UI under the `rules` tab as can be seen in the above image.

---

I hope this clarifies everything. I will be writing a new guide on Medium soon to replace my older article. This feedback helps me know where to focus.

Let me know if you have further issues.

**Comment by joshleong** [comment]
This is the error on windows.

```0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'deploy' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle dyna-stories-server@3.0.0~predeploy: dyna-stories-server@3.0.0
6 verbose lifecycle dyna-stories-server@3.0.0~predeploy: unsafe-perm in lifecycle true
7 verbose lifecycle dyna-stories-server@3.0.0~predeploy: PATH: C:\Users\joshl\AppData\Roaming\nvm\v10.13.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Development\dynastories-server\node_modules\.bin;C:\Python38\Scripts\;C:\Python38\;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin\;C:\Users\joshl\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\joshl\AppData\Local\Microsoft\WindowsApps;C:\Users\joshl\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\joshl\AppData\Local\GitHubDesktop\bin;C:\Users\joshl\AppData\Local\Yarn\bin;C:\Users\joshl\AppData\Roaming\npm;C:\Users\joshl\AppData\Roaming\nvm;C:\Program Files\nodejs
8 verbose lifecycle dyna-stories-server@3.0.0~predeploy: CWD: C:\Development\dynastories-server
9 silly lifecycle dyna-stories-server@3.0.0~predeploy: Args: [ '-c',
9 silly lifecycle   'npm run clean && next build && node ./scripts/export.js' ]
10 info lifecycle dyna-stories-server@3.0.0~predeploy: Failed to exec predeploy script
11 silly lifecycle dyna-stories-server@3.0.0~predeploy: Returned: code: -4058  signal: null
12 info lifecycle dyna-stories-server@3.0.0~predeploy: Failed to exec predeploy script
13 verbose stack Error: dyna-stories-server@3.0.0 predeploy: `npm run clean && next build && node ./scripts/export.js`
13 verbose stack spawn = ENOENT
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
13 verbose stack     at onErrorNT (internal/child_process.js:407:16)
13 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
14 verbose pkgid dyna-stories-server@3.0.0
15 verbose cwd C:\Development\dynastories-server
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "deploy"
18 verbose node v10.13.0
19 verbose npm  v6.4.1
20 error file =
21 error path =
22 error code ELIFECYCLE
23 error errno ENOENT
24 error syscall spawn =
25 error dyna-stories-server@3.0.0 predeploy: `npm run clean && next build && node ./scripts/export.js`
25 error spawn = ENOENT
26 error Failed at the dyna-stories-server@3.0.0 predeploy script.
26 error This is probably not a problem with npm. There is likely additional logging output above.
27 verbose exit [ 1, true ]```

**Comment by jthegedus** [comment]
Well, I've no idea from that error output 🤷 

Perhaps try running each of those commands individually:

```
npm run clean
next build
node ./scripts/export.js
```

**Comment by joshleong** [comment]
Yeah I'm not sure, but I have things running in Ubuntu just fine, and I got your last sample to work also perfectly so I might go forward with that for a bit.

I think I've mostly got everything to work.

<img width="1361" alt="successfuldeploy" src="https://user-images.githubusercontent.com/229303/81042186-6aecd080-8e64-11ea-8d30-bf125e74196c.PNG">

But for some reason there is no redirect from the hosting page.

**Comment by jthegedus** [comment]
You need to fix your `hosting` configuration:

```
  "hosting": {
    "site": "TODO_YOUR_WEB_APP_DEPLOY_TARGET_HERE",
    "public": "out/",
    "cleanUrls": true,
    "rewrites": [
      {
        "source": "**",
        "function": "nextjs-server"
      }
    ]
  }
```

The `out/` dir is what you want to deploy to Firebase. The `public/` dir is used by next.js and we compile the app and then move all static assets to the `out/` dir.

Also, you're missing your `rewrites` and `cleanUrls`

**Comment by joshleong** [comment]
🤦‍♂️🤦‍♂️🤦‍♂️

Thanks James, it totally works! With Firestore as well now! This is amazing!

**Comment by jthegedus** [comment]
Sweet, I am glad it works! Checkout the rest of the readme, especially the `future` section for my recommendations going forward for React & Firebase etc

**Comment by joshleong** [comment]
Hey James, are you having any issues with hot-reloading? I'm currently trying to use nodemon, but it also doesn't seem to be working.

**Comment by jthegedus** [comment]
I have not had any issues with hot-reloading with `next dev`. The `server.js` is intended to be the small glue between Next.js and Cloud Functions. I haven't tested any hot-reloading with the server.

**Comment by joshleong** [comment]
Haha no prob happy to have the opportunity to support.

Hmm yeah weird, hot reloading isn't working for me right now, oh well I'll just bite the bullet for now, everything else seems good.

**Comment by jthegedus** [comment]
@joshleong Hey mate, I found a bug in the `scripts/export.js` script, so you might want to resync that file with what's in `master` now.

Also, have you tried the `firebase emulators:start` method, I believe the firebase emulator has hot reloading for the Firebase Functions code (in this case `server.js`), though I didn't investigate this in depth, it seemed to be very buggy.

**Comment by eduncan911** [comment]
> You need to fix your `hosting` configuration:
> 
> ```
>   "hosting": {
>     "site": "TODO_YOUR_WEB_APP_DEPLOY_TARGET_HERE",
>     "public": "out/",
>     "cleanUrls": true,
>     "rewrites": [
>       {
>         "source": "**",
>         "function": "nextjs-server"
>       }
>     ]
>   }
> ```
> 
> The `out/` dir is what you want to deploy to Firebase. The `public/` dir is used by next.js and we compile the app and then move all static assets to the `out/` dir.
> 

I'm scratching my head on this recommendation though with Firebase static Hosting and Functions.  Yes, that would work.  

However, aren't you directing all traffic - including all static assets and requests - through the functions?  Therefore, greatly increasing the costs of each request?

Firebase static site Hosting + Function hosting explains it that if your `public` location has a static file, it will be served first by the static file - and it will not be passed to the functions.  

From my other firebase Hosting deployments, that location is the `public` in the json of the following:

```
  "hosting": {
    "site": "TODO_YOUR_WEB_APP_DEPLOY_TARGET_HERE",
    "public": "out/",
    "cleanUrls": true,
    "rewrites": [
      {
        "source": "**",
        "function": "nextjs-server"
      }
    ]
  }
```

However, if you are pointing to the `out` directory for the static site content, and that content does not exist, Firebase will push it all through the Function (server-side) request - which, nextjs will see as a static asset and serve it up.

But the point is, that's a function request !!  Regardless if the "nextjs App" serves up a static asset, or an SSR or any other request. I believe this all goes through the functions request.

You can test this out by doing the following:

    # make a new completely static folder
    mkdir ./publish
    # copy existing assets to the publishing folder
    cp -r ./public/ ./publish/
    # copy the auto-generated nextjs static pages
    cp -r out/server/pages/ ./publish/

Then, change your Hosting to point to publish:

```
"hosting": {
    "site": "TODO_YOUR_WEB_APP_DEPLOY_TARGET_HERE",
    "public": "publish/",
    "cleanUrls": true,
    "rewrites": [
      {
        "source": "**",
        "function": "nextjs-server"
      }
    ]
  }
```

Now, Firebase any request to a static html page, asset, etc will be served by Firebase static site hosting - not touching `functions` at all.  Only if the asset/file does not exist, does it get routed to the `function` app you have defined.

If I am wrong here, and Firebase static site hosting knows how to handle `nextjs`'s location for static access (`out/server/pages/` + `public/` merged together), then please correct me.

Because I can't see how Firebase static site hosting can merge the `public/` assets with `out/server/pages/` in order to serve up completely static content - without functions.
