### ISSUE TITLE
getInitialProps ?

### ISSUE THREAD

**Issue by tlenoir** [jthegedus/firebase-gcp-examples#85]
_app.js and test.js to render a static page with props.local. I used getInitialProps method to render that. But failed when i want to serve with yarn.

> test.js

```
import React from 'react';
import App from "../components/App";
import TestComponent from "../components/Test";

function Test({ local }) {
    return (
        <App>
            <TestComponent local={local} />
        </App>
    )
}

export default Test.getInitialProps = () => {
    return { local: "Hello" };
}
```

The TestComponent just print the props.local

```
import React from 'react';

function Test({ local }) {
    return (
        <div>
            {local}
        </div>
    )
}

export default Test;
```

> _app.js

```
import React from 'react';

export default function MyApp({ Component, pageProps, router }) {
    return (
        <React.Fragment>
            <Component {...pageProps} key={router.route} />
        </React.Fragment>
    )
}
```

> when i run yarn build

`
Creating an optimized production build  

Compiled successfully.

Automatically optimizing pages ..
Error occurred prerendering page "/test" https://err.sh/zeit/next.js/prerender-error: Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Blocal%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (/home/lenoir/vscode/firebase-gcp-examples/functions-nextjs/node_modules/react/cjs/react.production.min.js:19:94)
    at U (/home/lenoir/vscode/firebase-gcp-examples/functions-nextjs/node_modules/react/cjs/react.production.min.js:19:229)
    at V (/home/lenoir/vscode/firebase-gcp-examples/functions-nextjs/node_modules/react/cjs/react.production.min.js:20:322)
    at toArray (/home/lenoir/vscode/firebase-gcp-examples/functions-nextjs/node_modules/react/cjs/react.production.min.js:21:261)
    at a.b.render (/home/lenoir/vscode/firebase-gcp-examples/functions-nextjs/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:45:176)
    at a.b.read (/home/lenoir/vscode/firebase-gcp-examples/functions-nextjs/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/home/lenoir/vscode/firebase-gcp-examples/functions-nextjs/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at render (/home/lenoir/vscode/firebase-gcp-examples/functions-nextjs/node_modules/next/dist/next-server/server/render.js:81:16)
    at Object.renderPage (/home/lenoir/vscode/firebase-gcp-examples/functions-nextjs/node_modules/next/dist/next-server/server/render.js:346:16)
    at Function.getInitialProps (/home/lenoir/vscode/firebase-gcp-examples/functions-nextjs/dist/client/server/static/hSYgXCax9LBSjUtbkhXQ8/pages/_document.js:243:19)
> Build error occurred
Error: Export encountered errors
    at _default (/home/lenoir/vscode/firebase-gcp-examples/functions-nextjs/node_modules/next/dist/export/index.js:19:811)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
`

**Comment by jthegedus** [comment]
This is a question better asked on the Next.js repo. I hope you solved your issue in the meantime.
